package assignment;

import java.awt.Color;
import java.awt.Component;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class DeleteMedicine extends javax.swing.JFrame {

    private Component frame;

    public DeleteMedicine() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        medicineDetails_Pnl.setVisible(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        medicineDetails_Pnl = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        detail_price_txt = new javax.swing.JTextField();
        detail_medicineId_txt = new javax.swing.JTextField();
        detail_quantity_txt = new javax.swing.JTextField();
        detail_MedicineName_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        delete_btn = new javax.swing.JButton();
        detail_companyName_txt = new javax.swing.JTextField();
        cancel_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        detail_batch_txt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        detail_DOE_dateChooser = new datechooser.beans.DateChooserCombo();
        jLabel6 = new javax.swing.JLabel();
        detail_DOM_dateChooser = new datechooser.beans.DateChooserCombo();
        search_pnl = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        medicineName_txt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        OK_btn = new javax.swing.JButton();
        close_btn = new javax.swing.JButton();
        medicineId_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Delete Medicine");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(606, 610));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Delete Medicine");

        medicineDetails_Pnl.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel7.setText("DOE");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel8.setText("RM");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel2.setText("Medicine ID");

        detail_price_txt.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        detail_price_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detail_price_txtActionPerformed(evt);
            }
        });
        detail_price_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                detail_price_txtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                detail_price_txtKeyTyped(evt);
            }
        });

        detail_medicineId_txt.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        detail_medicineId_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detail_medicineId_txtActionPerformed(evt);
            }
        });

        detail_quantity_txt.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        detail_quantity_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detail_quantity_txtActionPerformed(evt);
            }
        });
        detail_quantity_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                detail_quantity_txtKeyPressed(evt);
            }
        });

        detail_MedicineName_txt.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        detail_MedicineName_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detail_MedicineName_txtActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel9.setText("Quantity");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel3.setText("Medicine Name");

        delete_btn.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        delete_btn.setText("Delete");
        delete_btn.setFocusable(false);
        delete_btn.setPreferredSize(new java.awt.Dimension(104, 37));
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        detail_companyName_txt.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        detail_companyName_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detail_companyName_txtActionPerformed(evt);
            }
        });

        cancel_btn.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        cancel_btn.setText("Cancel");
        cancel_btn.setFocusable(false);
        cancel_btn.setMinimumSize(new java.awt.Dimension(104, 37));
        cancel_btn.setPreferredSize(new java.awt.Dimension(104, 37));
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel4.setText("Company");

        detail_batch_txt.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        detail_batch_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detail_batch_txtActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel10.setText("Price");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel5.setText("Batch");

        detail_DOE_dateChooser.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    detail_DOE_dateChooser.setCalendarPreferredSize(new java.awt.Dimension(380, 250));
    detail_DOE_dateChooser.setFieldFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 20));
    detail_DOE_dateChooser.setNavigateFont(new java.awt.Font("Serif", java.awt.Font.PLAIN, 20));

    jLabel6.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
    jLabel6.setText("DOM");

    detail_DOM_dateChooser.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
        new datechooser.view.appearance.ViewAppearance("custom",
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                true,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 255),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(128, 128, 128),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(255, 0, 0),
                false,
                false,
                new datechooser.view.appearance.swing.ButtonPainter()),
            (datechooser.view.BackRenderer)null,
            false,
            true)));
detail_DOM_dateChooser.setCalendarPreferredSize(new java.awt.Dimension(380, 250));
detail_DOM_dateChooser.setFormat(2);
detail_DOM_dateChooser.setFieldFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 20));
detail_DOM_dateChooser.setNavigateFont(new java.awt.Font("Serif", java.awt.Font.PLAIN, 20));

javax.swing.GroupLayout medicineDetails_PnlLayout = new javax.swing.GroupLayout(medicineDetails_Pnl);
medicineDetails_Pnl.setLayout(medicineDetails_PnlLayout);
medicineDetails_PnlLayout.setHorizontalGroup(
    medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, medicineDetails_PnlLayout.createSequentialGroup()
        .addGap(10, 10, 10)
        .addGroup(medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicineDetails_PnlLayout.createSequentialGroup()
                .addGroup(medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(72, 72, 72)
                .addGroup(medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(medicineDetails_PnlLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(detail_price_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(detail_batch_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(detail_companyName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(detail_DOM_dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(detail_DOE_dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(detail_quantity_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(medicineDetails_PnlLayout.createSequentialGroup()
                        .addComponent(delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(medicineDetails_PnlLayout.createSequentialGroup()
                .addGroup(medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addGroup(medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detail_medicineId_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detail_MedicineName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap(50, Short.MAX_VALUE))
    );
    medicineDetails_PnlLayout.setVerticalGroup(
        medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(medicineDetails_PnlLayout.createSequentialGroup()
            .addGap(5, 5, 5)
            .addGroup(medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(detail_medicineId_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(10, 10, 10)
            .addGroup(medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(detail_MedicineName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(10, 10, 10)
            .addGroup(medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(detail_companyName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(10, 10, 10)
            .addGroup(medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(detail_batch_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(10, 10, 10)
            .addGroup(medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(detail_DOM_dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
            .addGap(10, 10, 10)
            .addGroup(medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(detail_DOE_dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(10, 10, 10)
            .addGroup(medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(detail_price_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel8)
                .addComponent(jLabel10))
            .addGap(10, 10, 10)
            .addGroup(medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel9)
                .addComponent(detail_quantity_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(20, 20, 20)
            .addGroup(medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
    );

    search_pnl.setBackground(new java.awt.Color(255, 255, 255));

    jLabel11.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
    jLabel11.setText("Medicine ID");

    medicineName_txt.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
    medicineName_txt.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            medicineName_txtActionPerformed(evt);
        }
    });

    jLabel12.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
    jLabel12.setText("Medicine Name");

    OK_btn.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
    OK_btn.setText("OK");
    OK_btn.setFocusable(false);
    OK_btn.setPreferredSize(new java.awt.Dimension(104, 37));
    OK_btn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            OK_btnActionPerformed(evt);
        }
    });

    close_btn.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
    close_btn.setText("Close");
    close_btn.setFocusable(false);
    close_btn.setPreferredSize(new java.awt.Dimension(104, 37));
    close_btn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            close_btnActionPerformed(evt);
        }
    });

    medicineId_txt.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
    medicineId_txt.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            medicineId_txtActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout search_pnlLayout = new javax.swing.GroupLayout(search_pnl);
    search_pnl.setLayout(search_pnlLayout);
    search_pnlLayout.setHorizontalGroup(
        search_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search_pnlLayout.createSequentialGroup()
            .addGroup(search_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(search_pnlLayout.createSequentialGroup()
                    .addGap(164, 164, 164)
                    .addComponent(OK_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                    .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search_pnlLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addGroup(search_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addComponent(jLabel11))
                    .addGap(18, 18, 18)
                    .addGroup(search_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(search_pnlLayout.createSequentialGroup()
                            .addComponent(medicineName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(medicineId_txt))))
            .addGap(51, 51, 51))
    );
    search_pnlLayout.setVerticalGroup(
        search_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(search_pnlLayout.createSequentialGroup()
            .addGap(5, 5, 5)
            .addGroup(search_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel11)
                .addComponent(medicineId_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(10, 10, 10)
            .addGroup(search_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel12)
                .addComponent(medicineName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(20, 20, 20)
            .addGroup(search_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(OK_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap(83, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(medicineDetails_Pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(search_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(80, Short.MAX_VALUE))
        .addGroup(layout.createSequentialGroup()
            .addGap(50, 50, 50)
            .addComponent(jLabel1)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
            .addComponent(search_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(medicineDetails_Pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(30, Short.MAX_VALUE))
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void medicineName_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineName_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicineName_txtActionPerformed

    private void OK_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OK_btnActionPerformed

        enablefields();
        Pharmacist phar = new Pharmacist();
        try {
            if (assignMedicineDetails()) {
                search_pnl.setVisible(false);
                medicineDetails_Pnl.setVisible(true);
                
            } else {
                JOptionPane.showMessageDialog(frame, "Can't find the medicine.\n"
                        + "Please, make sure that you have entered a correct "
                        + "medicine ID and Name",
                        "Invalid Entry!",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (ParseException ex) {
            Logger.getLogger(DeleteMedicine.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DeleteMedicine.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_OK_btnActionPerformed

    private void close_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_btnActionPerformed
        this.dispose();
    }//GEN-LAST:event_close_btnActionPerformed

    private void medicineId_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineId_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicineId_txtActionPerformed

    private void detail_price_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detail_price_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detail_price_txtActionPerformed

    private void detail_price_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_detail_price_txtKeyPressed

    }//GEN-LAST:event_detail_price_txtKeyPressed

    private void detail_price_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_detail_price_txtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_detail_price_txtKeyTyped

    private void detail_medicineId_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detail_medicineId_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detail_medicineId_txtActionPerformed

    private void detail_quantity_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detail_quantity_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detail_quantity_txtActionPerformed

    private void detail_quantity_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_detail_quantity_txtKeyPressed

    }//GEN-LAST:event_detail_quantity_txtKeyPressed

    private void detail_MedicineName_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detail_MedicineName_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detail_MedicineName_txtActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        Pharmacist phr = new Pharmacist();
        try {
            if (phr.deleteMedicine(medicineId_txt.getText(),
                    medicineName_txt.getText()) == true) {
                JOptionPane.showMessageDialog(frame, detail_medicineId_txt.getText()
                        + " has been deleted successfully",
                        "Successful Process", JOptionPane.INFORMATION_MESSAGE);
                medicineDetails_Pnl.setVisible(false);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(frame, detail_medicineId_txt.getText()
                        + " has not been modifies successfully",
                        "Faild Process", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException ex) {
            Logger.getLogger(DeleteMedicine.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_delete_btnActionPerformed

    private void detail_companyName_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detail_companyName_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detail_companyName_txtActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void detail_batch_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detail_batch_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detail_batch_txtActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteMedicine().setVisible(true);
            }
        });
    }

    private void enablefields() {
        detail_medicineId_txt.setEnabled(false);
        detail_MedicineName_txt.setEnabled(false);
        detail_DOE_dateChooser.setEnabled(false);
        detail_batch_txt.setEnabled(false);
        detail_companyName_txt.setEnabled(false);
        detail_price_txt.setEnabled(false);
        detail_quantity_txt.setEnabled(false);
        detail_DOM_dateChooser.setEnabled(false);
    }

    private boolean assignMedicineDetails() throws IOException, ParseException {
        boolean success = false;
        Pharmacist phar = new Pharmacist();
        ArrayList<String> details = new ArrayList();
        TxtFile mdc = new TxtFile("medicine.txt");
        details = mdc.getMedicineDetailsFromFile(medicineId_txt.getText(),
                medicineName_txt.getText());
        if (details.get(0).equals("true")) {
            Calendar domCal = Calendar.getInstance();
            Calendar doeCal = Calendar.getInstance();
            SimpleDateFormat sdf = new SimpleDateFormat("MMM dd, yyyy", Locale.ENGLISH);
            domCal.setTime(sdf.parse(details.get(5)));
            doeCal.setTime(sdf.parse(details.get(6)));
            success = true;
            detail_medicineId_txt.setText(details.get(1));
            detail_MedicineName_txt.setText(details.get(2));
            detail_companyName_txt.setText(details.get(3));
            detail_batch_txt.setText(details.get(4));
            detail_DOM_dateChooser.setSelectedDate(domCal);
            detail_DOE_dateChooser.setSelectedDate(doeCal);
            detail_price_txt.setText(details.get(7));
            detail_quantity_txt.setText(details.get(8));
        }
        return success;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OK_btn;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JButton close_btn;
    private javax.swing.JButton delete_btn;
    private datechooser.beans.DateChooserCombo detail_DOE_dateChooser;
    private datechooser.beans.DateChooserCombo detail_DOM_dateChooser;
    private javax.swing.JTextField detail_MedicineName_txt;
    private javax.swing.JTextField detail_batch_txt;
    private javax.swing.JTextField detail_companyName_txt;
    private javax.swing.JTextField detail_medicineId_txt;
    private javax.swing.JTextField detail_price_txt;
    private javax.swing.JTextField detail_quantity_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel medicineDetails_Pnl;
    private javax.swing.JTextField medicineId_txt;
    private javax.swing.JTextField medicineName_txt;
    private javax.swing.JPanel search_pnl;
    // End of variables declaration//GEN-END:variables
}
