package assignment;

import java.awt.Color;
import java.awt.Component;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class ModifyMedicine extends javax.swing.JFrame {

    private Component frame;

    /**
     * Creates new form ModifyMedicine
     */
    public ModifyMedicine() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        medicineDetails_Pnl.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        medicineDetails_Pnl = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        price_txt = new javax.swing.JTextField();
        newMedicineId_txt = new javax.swing.JTextField();
        quantity_txt = new javax.swing.JTextField();
        newMedicineName_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        modify_btn = new javax.swing.JButton();
        companyName_txt = new javax.swing.JTextField();
        cancel_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        clear_btn = new javax.swing.JButton();
        batch_txt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DOE_dateChooser = new datechooser.beans.DateChooserCombo();
        jLabel6 = new javax.swing.JLabel();
        DOM_dateChooser = new datechooser.beans.DateChooserCombo();
        search_pnl = new javax.swing.JPanel();
        oldMedicineId_txt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        oldmedicineName_txt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        OK_btn = new javax.swing.JButton();
        close_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modify Medicine");
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(645, 610));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Modify Medicine");

        medicineDetails_Pnl.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel7.setText("DOE");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel8.setText("RM");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel2.setText("Medicine ID");

        price_txt.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        price_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price_txtActionPerformed(evt);
            }
        });
        price_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                price_txtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                price_txtKeyTyped(evt);
            }
        });

        newMedicineId_txt.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        newMedicineId_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMedicineId_txtActionPerformed(evt);
            }
        });

        quantity_txt.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        quantity_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantity_txtActionPerformed(evt);
            }
        });
        quantity_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                quantity_txtKeyPressed(evt);
            }
        });

        newMedicineName_txt.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        newMedicineName_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMedicineName_txtActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel9.setText("Quantity");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel3.setText("Medicine Name");

        modify_btn.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        modify_btn.setText("Modify");
        modify_btn.setFocusable(false);
        modify_btn.setPreferredSize(new java.awt.Dimension(104, 37));
        modify_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modify_btnActionPerformed(evt);
            }
        });

        companyName_txt.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        companyName_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyName_txtActionPerformed(evt);
            }
        });

        cancel_btn.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        cancel_btn.setText("Cancel");
        cancel_btn.setFocusable(false);
        cancel_btn.setMinimumSize(new java.awt.Dimension(104, 37));
        cancel_btn.setPreferredSize(new java.awt.Dimension(104, 37));
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel4.setText("Company");

        clear_btn.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        clear_btn.setText("Clear");
        clear_btn.setFocusable(false);
        clear_btn.setPreferredSize(new java.awt.Dimension(104, 37));
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });

        batch_txt.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        batch_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batch_txtActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel10.setText("Price");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel5.setText("Batch");

        DOE_dateChooser.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    DOE_dateChooser.setCalendarPreferredSize(new java.awt.Dimension(380, 250));
    DOE_dateChooser.setFieldFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 20));
    DOE_dateChooser.setMinDate(DOM_dateChooser.getSelectedDate());
    DOE_dateChooser.setNavigateFont(new java.awt.Font("Serif", java.awt.Font.PLAIN, 20));

    jLabel6.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
    jLabel6.setText("DOM");

    DOM_dateChooser.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
        new datechooser.view.appearance.ViewAppearance("custom",
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                true,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 255),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(128, 128, 128),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(255, 0, 0),
                false,
                false,
                new datechooser.view.appearance.swing.ButtonPainter()),
            (datechooser.view.BackRenderer)null,
            false,
            true)));
DOM_dateChooser.setCalendarPreferredSize(new java.awt.Dimension(380, 250));
DOM_dateChooser.setFormat(2);
DOM_dateChooser.setFieldFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 20));
DOM_dateChooser.setNavigateFont(new java.awt.Font("Serif", java.awt.Font.PLAIN, 20));

javax.swing.GroupLayout medicineDetails_PnlLayout = new javax.swing.GroupLayout(medicineDetails_Pnl);
medicineDetails_Pnl.setLayout(medicineDetails_PnlLayout);
medicineDetails_PnlLayout.setHorizontalGroup(
    medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, medicineDetails_PnlLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicineDetails_PnlLayout.createSequentialGroup()
                .addGroup(medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addGroup(medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newMedicineName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newMedicineId_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(medicineDetails_PnlLayout.createSequentialGroup()
                .addGroup(medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(72, 72, 72)
                .addGroup(medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(medicineDetails_PnlLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(batch_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(companyName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DOM_dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DOE_dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantity_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(medicineDetails_PnlLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(modify_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(25, 25, 25))
    );
    medicineDetails_PnlLayout.setVerticalGroup(
        medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(medicineDetails_PnlLayout.createSequentialGroup()
            .addGap(5, 5, 5)
            .addGroup(medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(newMedicineId_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(10, 10, 10)
            .addGroup(medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(newMedicineName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(10, 10, 10)
            .addGroup(medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(companyName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel4))
            .addGap(10, 10, 10)
            .addGroup(medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(batch_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5))
            .addGap(10, 10, 10)
            .addGroup(medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(DOM_dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(10, 10, 10)
            .addGroup(medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(DOE_dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(10, 10, 10)
            .addGroup(medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel8)
                .addComponent(jLabel10)
                .addComponent(price_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(10, 10, 10)
            .addGroup(medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel9)
                .addComponent(quantity_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(medicineDetails_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(modify_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    search_pnl.setBackground(new java.awt.Color(255, 255, 255));

    oldMedicineId_txt.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
    oldMedicineId_txt.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            oldMedicineId_txtActionPerformed(evt);
        }
    });

    jLabel11.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
    jLabel11.setText("Medicine ID");

    oldmedicineName_txt.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
    oldmedicineName_txt.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            oldmedicineName_txtActionPerformed(evt);
        }
    });

    jLabel12.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
    jLabel12.setText("Medicine Name");

    OK_btn.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
    OK_btn.setText("OK");
    OK_btn.setFocusable(false);
    OK_btn.setPreferredSize(new java.awt.Dimension(104, 37));
    OK_btn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            OK_btnActionPerformed(evt);
        }
    });

    close_btn.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
    close_btn.setText("Close");
    close_btn.setFocusable(false);
    close_btn.setPreferredSize(new java.awt.Dimension(104, 37));
    close_btn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            close_btnActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout search_pnlLayout = new javax.swing.GroupLayout(search_pnl);
    search_pnl.setLayout(search_pnlLayout);
    search_pnlLayout.setHorizontalGroup(
        search_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(search_pnlLayout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addGroup(search_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search_pnlLayout.createSequentialGroup()
                    .addComponent(OK_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(search_pnlLayout.createSequentialGroup()
                    .addGroup(search_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addComponent(jLabel11))
                    .addGap(20, 20, 20)
                    .addGroup(search_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(oldMedicineId_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                        .addComponent(oldmedicineName_txt))))
            .addGap(92, 92, 92))
    );
    search_pnlLayout.setVerticalGroup(
        search_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(search_pnlLayout.createSequentialGroup()
            .addGap(5, 5, 5)
            .addGroup(search_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel11)
                .addComponent(oldMedicineId_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(10, 10, 10)
            .addGroup(search_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(oldmedicineName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel12))
            .addGap(20, 20, 20)
            .addGroup(search_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(OK_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(80, 80, 80)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(search_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(medicineDetails_Pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(jLabel1)))
            .addContainerGap(83, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(26, 26, 26)
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
            .addComponent(search_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0)
            .addComponent(medicineDetails_Pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(30, Short.MAX_VALUE))
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void price_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price_txtActionPerformed

    private void price_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_price_txtKeyPressed

    }//GEN-LAST:event_price_txtKeyPressed

    private void price_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_price_txtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_price_txtKeyTyped

    private void newMedicineId_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMedicineId_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newMedicineId_txtActionPerformed

    private void quantity_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantity_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantity_txtActionPerformed

    private void quantity_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantity_txtKeyPressed

    }//GEN-LAST:event_quantity_txtKeyPressed

    private void newMedicineName_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMedicineName_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newMedicineName_txtActionPerformed

    private void modify_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modify_btnActionPerformed
        if (checkFields()) {
            Pharmacist phr = new Pharmacist();
            try {
                if (phr.modifyMedicine(oldMedicineId_txt.getText(),
                        oldmedicineName_txt.getText(), newMedicineId_txt.getText(),
                        newMedicineName_txt.getText(), companyName_txt.getText(),
                        Integer.parseInt(batch_txt.getText()), DOM_dateChooser.getText(),
                        DOE_dateChooser.getText(), Double.parseDouble(price_txt.getText()),
                        Integer.parseInt(quantity_txt.getText())) == true) {
                    JOptionPane.showMessageDialog(frame, newMedicineId_txt.getText()
                            + " has been modifies successfully",
                            "Successful Process", JOptionPane.INFORMATION_MESSAGE);
                    medicineDetails_Pnl.setVisible(false);
                    oldMedicineId_txt.setEnabled(true);
                    oldmedicineName_txt.setEnabled(true);
                    OK_btn.setEnabled(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(frame, newMedicineId_txt.getText()
                            + " has not been modifies successfully",
                            "Faild Process", JOptionPane.ERROR_MESSAGE);
                }
            } catch (IOException ex) {
                Logger.getLogger(ModifyMedicine.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_modify_btnActionPerformed

    private void companyName_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyName_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyName_txtActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        clearFields();
    }//GEN-LAST:event_clear_btnActionPerformed

    private void batch_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batch_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batch_txtActionPerformed

    private void oldMedicineId_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldMedicineId_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldMedicineId_txtActionPerformed

    private void oldmedicineName_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldmedicineName_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldmedicineName_txtActionPerformed

    private void OK_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OK_btnActionPerformed

        clearFields();
        try {
            Pharmacist phar = new Pharmacist();
            try {
                if (assignMedicineDetails()) {
                    search_pnl.setVisible(false);
                    medicineDetails_Pnl.setVisible(true);
                    oldMedicineId_txt.setEnabled(false);
                    oldmedicineName_txt.setEnabled(false);
                    OK_btn.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(frame, "Can't find the medicine.\n"
                            + "Please, make sure that you have entered a correct "
                            + "medicine ID and Name",
                            "Invalid Entry!",
                            JOptionPane.ERROR_MESSAGE);
                }
            } catch (ParseException ex) {
                Logger.getLogger(ModifyMedicine.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IOException ex) {
            Logger.getLogger(ModifyMedicine.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_OK_btnActionPerformed

    private void close_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_btnActionPerformed
        this.dispose();
    }//GEN-LAST:event_close_btnActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyMedicine().setVisible(true);
            }
        });
    }

    private boolean assignMedicineDetails() throws IOException, ParseException {
        boolean success = false;
        Pharmacist phar = new Pharmacist();
        ArrayList<String> details = new ArrayList();
        TxtFile mdc = new TxtFile("medicine.txt");
        details = mdc.getMedicineDetailsFromFile(oldMedicineId_txt.getText(),
                oldmedicineName_txt.getText());
        if (details.get(0).equals("true")) {
            Calendar domCal = Calendar.getInstance();
            Calendar doeCal = Calendar.getInstance();
            SimpleDateFormat sdf = new SimpleDateFormat("MMM dd, yyyy", Locale.ENGLISH);
            domCal.setTime(sdf.parse(details.get(5)));
            doeCal.setTime(sdf.parse(details.get(6)));
            success = true;
            newMedicineId_txt.setText(details.get(1));
            newMedicineName_txt.setText(details.get(2));
            companyName_txt.setText(details.get(3));
            batch_txt.setText(details.get(4));
            DOM_dateChooser.setSelectedDate(domCal);
            DOE_dateChooser.setSelectedDate(doeCal);
            price_txt.setText(details.get(7));
            quantity_txt.setText(details.get(8));
        }
        return success;
    }

    private boolean checkFields() {
        boolean success = false;
        if (newMedicineId_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(frame, "Please, make sure that you "
                    + "have entered the medecine ID",
                    "Invalid Entry!",
                    JOptionPane.ERROR_MESSAGE);
            newMedicineId_txt.requestFocusInWindow();
        } else if (newMedicineName_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(frame, "Please, make sure that you "
                    + "have entered the medicine name",
                    "Invalid Entry!",
                    JOptionPane.ERROR_MESSAGE);
            newMedicineName_txt.requestFocusInWindow();
        } else if (companyName_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(frame, "Please, make sure that you "
                    + "have entered the company name",
                    "Invalid Entry!",
                    JOptionPane.ERROR_MESSAGE);
            companyName_txt.requestFocusInWindow();
        } else if (batch_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(frame, "Please, make sure that you "
                    + "have entered the batch",
                    "Invalid Entry!",
                    JOptionPane.ERROR_MESSAGE);
            batch_txt.requestFocusInWindow();
        } else {
            
            try {
                Double.parseDouble(price_txt.getText());
                success = true;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(frame, "Please, make sure that you "
                        + "have entered a correct price. Text filed only accepts numbers.",
                        "Invalid Entry!",
                        JOptionPane.ERROR_MESSAGE);
                price_txt.requestFocusInWindow();
                return false;
            }
            
            try {
                Integer.parseInt(batch_txt.getText());
                success = true;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(frame, "Please, make sure that you "
                        + "have entered correct batch number. Text filed only accepts numbers. ",
                        "Invalid Entry!",
                        JOptionPane.ERROR_MESSAGE);
                batch_txt.requestFocusInWindow();
                return false;
            }

            try {
                Integer.parseInt(quantity_txt.getText());
                success = true;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(frame, "Please, make sure that you "
                        + "have entered correct quantity number. Text filed only accepts numbers. ",
                        "Invalid Entry!",
                        JOptionPane.ERROR_MESSAGE);
                quantity_txt.requestFocusInWindow();
                return false;
            }

        }
        return success;
    }

    private void clearFields() {
        newMedicineId_txt.setText(null);
        newMedicineName_txt.setText(null);
        companyName_txt.setText(null);
        batch_txt.setText(null);
        price_txt.setText(null);
        quantity_txt.setText(null);
        DOE_dateChooser.setSelectedDate(Calendar.getInstance());
        DOM_dateChooser.setSelectedDate(Calendar.getInstance());
        newMedicineId_txt.requestFocusInWindow();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo DOE_dateChooser;
    private datechooser.beans.DateChooserCombo DOM_dateChooser;
    private javax.swing.JButton OK_btn;
    private javax.swing.JTextField batch_txt;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JButton clear_btn;
    private javax.swing.JButton close_btn;
    private javax.swing.JTextField companyName_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel medicineDetails_Pnl;
    private javax.swing.JButton modify_btn;
    private javax.swing.JTextField newMedicineId_txt;
    private javax.swing.JTextField newMedicineName_txt;
    private javax.swing.JTextField oldMedicineId_txt;
    private javax.swing.JTextField oldmedicineName_txt;
    private javax.swing.JTextField price_txt;
    private javax.swing.JTextField quantity_txt;
    private javax.swing.JPanel search_pnl;
    // End of variables declaration//GEN-END:variables

}
