package assignment;

import java.awt.Color;
import java.awt.Component;
import java.io.IOException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class SearchMedicine extends javax.swing.JFrame {

    String userRole = Login.role;
    private Component frame;

    /**
     * Creates new form SearchMedicine
     */
    public SearchMedicine() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        result_txtArea.setVisible(false);
        unavailable_lbl.setVisible(false);
        availabe_lbl.setVisible(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        medicineId_txt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        medicineName_txt = new javax.swing.JTextField();
        search_btn = new javax.swing.JButton();
        close_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        result_txtArea = new javax.swing.JTextArea();
        availabe_lbl = new javax.swing.JLabel();
        unavailable_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Search Medicine");
        setLocationByPlatform(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Search Medicine");

        medicineId_txt.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        medicineId_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineId_txtActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel11.setText("Medicine ID");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel12.setText("Medicine Name");

        medicineName_txt.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        medicineName_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineName_txtActionPerformed(evt);
            }
        });

        search_btn.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        search_btn.setText("Search");
        search_btn.setFocusable(false);
        search_btn.setPreferredSize(new java.awt.Dimension(104, 37));
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });

        close_btn.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        close_btn.setText("Close");
        close_btn.setFocusable(false);
        close_btn.setPreferredSize(new java.awt.Dimension(104, 37));
        close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_btnActionPerformed(evt);
            }
        });

        result_txtArea.setColumns(20);
        result_txtArea.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        result_txtArea.setRows(5);
        jScrollPane1.setViewportView(result_txtArea);

        availabe_lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        availabe_lbl.setForeground(new java.awt.Color(33, 175, 123));
        availabe_lbl.setText("Available");

        unavailable_lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        unavailable_lbl.setForeground(new java.awt.Color(255, 0, 23));
        unavailable_lbl.setText("Unvailable");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(medicineId_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                    .addComponent(medicineName_txt)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(availabe_lbl)
                                .addGap(31, 31, 31)
                                .addComponent(unavailable_lbl))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(medicineId_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(medicineName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(availabe_lbl)
                    .addComponent(unavailable_lbl))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void medicineId_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineId_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicineId_txtActionPerformed

    private void medicineName_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineName_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicineName_txtActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        try {
            result_txtArea.setText("");
            if (assignMedicineDetails()) {
                result_txtArea.setVisible(true);
            } else {
                unavailable_lbl.setVisible(true);
                availabe_lbl.setVisible(false);
                result_txtArea.setVisible(false);
                JOptionPane.showMessageDialog(frame, "Can't find the medicine.\n"
                        + "Please, make sure that you have entered a correct "
                        + "medicine ID and Name",
                        "Invalid Entry!",
                        JOptionPane.ERROR_MESSAGE);

            }
        } catch (IOException ex) {
            Logger.getLogger(SearchMedicine.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(SearchMedicine.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_search_btnActionPerformed

    private void close_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_btnActionPerformed
        this.dispose();
    }//GEN-LAST:event_close_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchMedicine().setVisible(true);
            }
        });
    }

    private boolean assignMedicineDetails() throws IOException, ParseException {
        boolean success = false;
        ArrayList<String> details = new ArrayList();
        if (userRole.equalsIgnoreCase("customer")) {
            Customer cus = new Customer();
            details = cus.searchMedicine(medicineId_txt.getText(),
                    medicineName_txt.getText());
            if (details.get(0).equals("true")) {
                success = true;
                result_txtArea.append("Medicine ID: " + details.get(1) + "\n");
                result_txtArea.append("Medicine Name: " + details.get(2) + "\n");
                result_txtArea.append("Company Name: " + details.get(3) + "\n");
                result_txtArea.append("DOM : " + details.get(5) + "\n");
                result_txtArea.append("DOE : " + details.get(6) + "\n");
                result_txtArea.append("Price : " + details.get(7) + "\n");
                if (Integer.parseInt(details.get(8)) > 0) {
                    availabe_lbl.setVisible(true);
                    unavailable_lbl.setVisible(false);
                } else {
                    unavailable_lbl.setVisible(true);
                    availabe_lbl.setVisible(false);
                }
            }
        } else {
            Pharmacist phar = new Pharmacist();
            details = phar.searchMedicine(medicineId_txt.getText(),
                    medicineName_txt.getText());
            if (details.get(0).equals("true")) {
                success = true;
                result_txtArea.append("Medicine ID: " + details.get(1) + "\n");
                result_txtArea.append("Medicine Name: " + details.get(2) + "\n");
                result_txtArea.append("Company Name: " + details.get(3) + "\n");
                result_txtArea.append("Batch : " + details.get(4) + "\n");
                result_txtArea.append("DOM : " + details.get(6) + "\n");
                result_txtArea.append("DOE : " + details.get(6) + "\n");
                result_txtArea.append("Price : " + details.get(7) + "\n");
                result_txtArea.append("Quantity : " + details.get(8) + "\n");
                success = true;
                if (Integer.parseInt(details.get(8)) > 0) {
                    availabe_lbl.setVisible(true);
                    unavailable_lbl.setVisible(false);
                } else {
                    unavailable_lbl.setVisible(true);
                    availabe_lbl.setVisible(false);
                }

            }
        }
        return success;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availabe_lbl;
    private javax.swing.JButton close_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField medicineId_txt;
    private javax.swing.JTextField medicineName_txt;
    private javax.swing.JTextArea result_txtArea;
    private javax.swing.JButton search_btn;
    private javax.swing.JLabel unavailable_lbl;
    // End of variables declaration//GEN-END:variables
}
