package assignment;

import java.awt.Color;
import java.awt.Component;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class UsersManagement extends javax.swing.JFrame {

    private Component frame;

    /**
     * Creates new form NewUser
     */
    public UsersManagement() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        addUser_pnl.setVisible(false);
        removeUser_pnl.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addUser_pnl = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        newUserNameTxt = new javax.swing.JTextField();
        pwdTxt = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rePwdTxt = new javax.swing.JPasswordField();
        roleCmb = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        add_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        cancel_btn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        email_txt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lastName_txt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        firstName_txt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        removeUser_pnl = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        users_cmb = new javax.swing.JComboBox();
        OK_btn1 = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        options_pnl = new javax.swing.JPanel();
        option_cmb = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        OK_btn = new javax.swing.JButton();
        close_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Users Management");
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(650, 600));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Users Management");

        addUser_pnl.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel2.setText("Username");

        newUserNameTxt.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        newUserNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserNameTxtActionPerformed(evt);
            }
        });

        pwdTxt.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        pwdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdTxtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel3.setText("Password");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel5.setText("Re- Write Password");

        rePwdTxt.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        rePwdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rePwdTxtActionPerformed(evt);
            }
        });

        roleCmb.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        roleCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pharmacist", "Customer" }));
        roleCmb.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel4.setText("Role");

        add_btn.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        add_btn.setText("Add");
        add_btn.setFocusable(false);
        add_btn.setPreferredSize(new java.awt.Dimension(101, 37));
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        clear_btn.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        clear_btn.setText("Clear");
        clear_btn.setFocusable(false);
        clear_btn.setPreferredSize(new java.awt.Dimension(101, 37));
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });

        cancel_btn.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        cancel_btn.setText("Cancel");
        cancel_btn.setFocusable(false);
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(33, 175, 123));
        jLabel8.setText("Add New User");

        email_txt.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        email_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_txtActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel10.setText("Email");

        lastName_txt.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lastName_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastName_txtActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel11.setText("Last Name");

        firstName_txt.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        firstName_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstName_txtActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel12.setText("First Name");

        javax.swing.GroupLayout addUser_pnlLayout = new javax.swing.GroupLayout(addUser_pnl);
        addUser_pnl.setLayout(addUser_pnlLayout);
        addUser_pnlLayout.setHorizontalGroup(
            addUser_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addUser_pnlLayout.createSequentialGroup()
                .addGroup(addUser_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addUser_pnlLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8))
                    .addGroup(addUser_pnlLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(addUser_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(20, 20, 20)
                        .addGroup(addUser_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(roleCmb, 0, 225, Short.MAX_VALUE)
                            .addComponent(rePwdTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(newUserNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(email_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(lastName_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(firstName_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(pwdTxt)))
                    .addGroup(addUser_pnlLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cancel_btn)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        addUser_pnlLayout.setVerticalGroup(
            addUser_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addUser_pnlLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(addUser_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(firstName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(addUser_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lastName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(addUser_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(addUser_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(newUserNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(addUser_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pwdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(addUser_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rePwdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(addUser_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(roleCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(addUser_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel_btn)
                    .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        removeUser_pnl.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel7.setText("Username");

        users_cmb.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        users_cmb.setToolTipText("");

        OK_btn1.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        OK_btn1.setText("Remove");
        OK_btn1.setFocusable(false);
        OK_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OK_btn1ActionPerformed(evt);
            }
        });

        cancelBtn.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.setFocusable(false);
        cancelBtn.setPreferredSize(new java.awt.Dimension(119, 37));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(33, 175, 123));
        jLabel9.setText("Remove User");

        javax.swing.GroupLayout removeUser_pnlLayout = new javax.swing.GroupLayout(removeUser_pnl);
        removeUser_pnl.setLayout(removeUser_pnlLayout);
        removeUser_pnlLayout.setHorizontalGroup(
            removeUser_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, removeUser_pnlLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(removeUser_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(removeUser_pnlLayout.createSequentialGroup()
                        .addComponent(OK_btn1)
                        .addGap(20, 20, 20)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(users_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(134, 134, 134))
            .addGroup(removeUser_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        removeUser_pnlLayout.setVerticalGroup(
            removeUser_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeUser_pnlLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(removeUser_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(users_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(removeUser_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OK_btn1)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        options_pnl.setBackground(new java.awt.Color(255, 255, 255));

        option_cmb.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        option_cmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Add New User", "Remove User" }));
        option_cmb.setToolTipText("");
        option_cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option_cmbActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel6.setText("Options");

        OK_btn.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        OK_btn.setText("OK");
        OK_btn.setFocusable(false);
        OK_btn.setPreferredSize(new java.awt.Dimension(101, 37));
        OK_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OK_btnActionPerformed(evt);
            }
        });

        close_btn.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        close_btn.setText("Close");
        close_btn.setFocusable(false);
        close_btn.setPreferredSize(new java.awt.Dimension(101, 37));
        close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout options_pnlLayout = new javax.swing.GroupLayout(options_pnl);
        options_pnl.setLayout(options_pnlLayout);
        options_pnlLayout.setHorizontalGroup(
            options_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, options_pnlLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(options_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(options_pnlLayout.createSequentialGroup()
                        .addComponent(OK_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(option_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        options_pnlLayout.setVerticalGroup(
            options_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(options_pnlLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(options_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(option_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(options_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OK_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(options_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeUser_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addUser_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(options_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(removeUser_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(addUser_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newUserNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newUserNameTxtActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        if (checkFields() == true) {
            Admin dmn = new Admin();
            try {
                if (dmn.addNewUser(firstName_txt.getText(), lastName_txt.getText(),
                        email_txt.getText(), newUserNameTxt.getText(),
                        String.valueOf(pwdTxt.getPassword()),
                        String.valueOf(roleCmb.getSelectedItem())) == true) {
                    JOptionPane.showMessageDialog(frame,
                            newUserNameTxt.getText() + " has added successfully as a new username",
                            "Successful Adding New User", JOptionPane.INFORMATION_MESSAGE);
                    clearFields();
                    addUser_pnl.setVisible(false);
                    this.dispose();
                }
            } catch (IOException ex) {
                Logger.getLogger(UsersManagement.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_add_btnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        clearFields();
    }//GEN-LAST:event_clear_btnActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void OK_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OK_btnActionPerformed
        if (option_cmb.getSelectedItem() == "Add New User") {
            addUser_pnl.setVisible(true);
            removeUser_pnl.setVisible(false);
            options_pnl.setVisible(false);
        } else {
            try {
                getUsersList();
                options_pnl.setVisible(false);
            } catch (IOException ex) {
                ex.getStackTrace();
            }
            addUser_pnl.setVisible(false);
            removeUser_pnl.setVisible(true);
        }
    }//GEN-LAST:event_OK_btnActionPerformed

    private void close_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_btnActionPerformed
        this.dispose();
    }//GEN-LAST:event_close_btnActionPerformed

    private void OK_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OK_btn1ActionPerformed
        Admin adm = new Admin();
        try {
            if (adm.removeUser(users_cmb.getSelectedItem().toString()) == true) {
                JOptionPane.showMessageDialog(frame, "The user had been removed"
                        + " successfully", "Successful Process", JOptionPane.INFORMATION_MESSAGE);
                getUsersList();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(frame, "Can not reomved the user"
                        + " currently. Please try again",
                        "Failed Process", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException ex) {
            Logger.getLogger(UsersManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_OK_btn1ActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void email_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_txtActionPerformed

    private void lastName_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastName_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastName_txtActionPerformed

    private void firstName_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstName_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstName_txtActionPerformed

    private void pwdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdTxtActionPerformed

    private void rePwdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rePwdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rePwdTxtActionPerformed

    private void option_cmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option_cmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_option_cmbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsersManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsersManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsersManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsersManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsersManagement().setVisible(true);
            }
        });
    }

    private void clearFields() {
        newUserNameTxt.setText(null);
        pwdTxt.setText(null);
        rePwdTxt.setText(null);
        roleCmb.setSelectedIndex(0);
        firstName_txt.requestFocusInWindow();
        firstName_txt.setText(null);
        lastName_txt.setText(null);
        email_txt.setText(null);
    }

    private boolean checkFields() {
        boolean success = false;
        if (firstName_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(frame, "Please, make sure that you "
                    + "have entered user's first name",
                    "Invalid Entry!",
                    JOptionPane.ERROR_MESSAGE);
        } else if (lastName_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(frame, "Please, make sure that you "
                    + "have entered user's last name",
                    "Invalid Entry!",
                    JOptionPane.ERROR_MESSAGE);
        } else if (!email_txt.getText().matches("[a-zA-Z0-9\\.]+@[a-zA-Z0-9\\-\\_\\.]+\\.[a-zA-Z0-9]{3}")) {
            JOptionPane.showMessageDialog(frame, "Please, make sure that you "
                    + "have entered a correct email address",
                    "Invalid Entry!",
                    JOptionPane.ERROR_MESSAGE);
        } else if (newUserNameTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(frame, "Please, make sure that you "
                    + "have entered the new username",
                    "Invalid Entry!",
                    JOptionPane.ERROR_MESSAGE);
        } else if (String.valueOf(pwdTxt.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(frame, "Please, make sure that you "
                    + "have entered the password",
                    "Invalid Entry!",
                    JOptionPane.ERROR_MESSAGE);
        } else if (String.valueOf(rePwdTxt.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(frame, "Please, make sure that you "
                    + "have re-written the password",
                    "Invalid Entry!",
                    JOptionPane.ERROR_MESSAGE);
        } else if (String.valueOf(pwdTxt.getPassword()) == null
                ? String.valueOf(rePwdTxt.getPassword()) != null
                : !String.valueOf(pwdTxt.getPassword()).equals(String.valueOf(rePwdTxt.getPassword()))) {
            JOptionPane.showMessageDialog(frame, "Please, Re-Write the password."
                    + "Password fields are not match",
                    "Invalid Entry!",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            success = true;
        }
        return success;
    }

    private void getUsersList() throws IOException {
        users_cmb.removeAllItems();
        TxtFile file = new TxtFile("users");
        ArrayList<String> list = new ArrayList<>();
        list = file.getUsersListFromFile();
        for (int i = 0; i < list.size(); i += 3) {
            users_cmb.addItem(list.get(i).substring(9));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OK_btn;
    private javax.swing.JButton OK_btn1;
    private javax.swing.JPanel addUser_pnl;
    private javax.swing.JButton add_btn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JButton clear_btn;
    private javax.swing.JButton close_btn;
    private javax.swing.JTextField email_txt;
    private javax.swing.JTextField firstName_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastName_txt;
    private javax.swing.JTextField newUserNameTxt;
    private javax.swing.JComboBox option_cmb;
    private javax.swing.JPanel options_pnl;
    private javax.swing.JPasswordField pwdTxt;
    private javax.swing.JPasswordField rePwdTxt;
    private javax.swing.JPanel removeUser_pnl;
    private javax.swing.JComboBox roleCmb;
    private javax.swing.JComboBox users_cmb;
    // End of variables declaration//GEN-END:variables
}
